version: 2.1

executors:
  frontend-executor:
    docker:
      - image: cimg/node:18.16.1

commands:
  setup-node-modules:
    description: "Restore node_modules"
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command:
            - yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  run-test:
    executor: frontend-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup-node-modules:
      - run:
          name: Run test
          command:
            - yarn test
  run-build:
    executor: frontend-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup-node-modules:
      - run:
          name: Run test
          command:
            - yarn test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test
